export const main = '/'
export const mainId = '/:id'
export const join = '/join'
export const login = '/login'
export const logout = '/logout'
export const lostPassword = '/password'
export const edit = '/edit/:id'
export const remove = '/delete/:id'
export const upload = '/upload'
export const watching = '/watch/:id'
export const search = '/search'
export const changePassword = '/password/:id'
export const addComment = '/add-comment'

