export const RESET_TYPE_MESSAGE = 'RESET_TYPE_MESSAGE'

export const AUTH_JOIN = 'AUTH_JOIN'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_LOST_PASSWORD = 'AUTH_LOST_PASSWORD'

export const VIDEOS_GET_ALL = 'VIDEOS_GET_ALL'
export const VIDEOS_GET_BY_ID = 'VIDEOS_GET_BY_ID'
export const VIDEOS_SEARCH = 'VIDEOS_SEARCH'
export const VIDEOS_EDIT = 'VIDEOS_EDIT'
export const VIDEOS_FOR_EDIT = 'VIDEOS_FOR_EDIT'
export const VIDEOS_DELETE = 'VIDEOS_DELETE'
export const VIDEOS_ADD_COMMENT = 'VIDEOS_ADD_COMMENT'
export const VIDEOS_UPLOAD = 'VIDEOS_UPLOAD'

export const HANDLE_EDIT_VIDEO = 'HANDLE_EDIT_VIDEO'

export const PROFILE_GET_BY_ID = 'PROFILE_GET_BY_ID'
export const PROFILE_EDIT = 'PROFILE_EDIT'
export const PROFILE_PASSWORD = 'PROFILE_PASSWORD'